//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace FriendsPortal.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FriendsPortalEntitiesContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FriendsPortalEntitiesContainer object using the connection string found in the 'FriendsPortalEntitiesContainer' section of the application configuration file.
        /// </summary>
        public FriendsPortalEntitiesContainer() : base("name=FriendsPortalEntitiesContainer", "FriendsPortalEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FriendsPortalEntitiesContainer object.
        /// </summary>
        public FriendsPortalEntitiesContainer(string connectionString) : base(connectionString, "FriendsPortalEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FriendsPortalEntitiesContainer object.
        /// </summary>
        public FriendsPortalEntitiesContainer(EntityConnection connection) : base(connection, "FriendsPortalEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

}
